import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-primary": "#bec6e0",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-highest": "#d3e4fe",
        "primary": "#000000",
        "tertiary-container": "#00210a",
        "on-tertiary-fixed": "#00210a",
        "surface-container": "#e5eeff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "primary-fixed": "#dae2fd",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed-variant": "#0039b5",
        "tertiary-fixed-dim": "#79db8d",
        "background": "#f8f9ff",
        "on-surface": "#0b1c30",
        "outline-variant": "#c6c6cd",
        "secondary-container": "#4069f2",
        "tertiary-fixed": "#95f8a7",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "outline": "#76777d",
        "on-background": "#0b1c30",
        "primary-container": "#131b2e",
        "secondary": "#1d4ed8",
        "secondary-fixed": "#dce1ff",
        "on-secondary-fixed": "#001551",
        "on-tertiary-fixed-variant": "#005323",
        "on-tertiary": "#ffffff",
        "surface-tint": "#565e74",
        "inverse-surface": "#213145",
        "on-tertiary-container": "#339650",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b7c4ff",
        "primary-fixed-dim": "#bec6e0",
        "surface": "#f8f9ff",
        "on-primary-container": "#7c839b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-sm": "0.5rem",
        "margin-compact": "0.5rem",
        "space-lg": "1rem",
        margin: "1rem",
        "gutter-dense": "0.5rem",
        gutter: "0.75rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-xl": "1.5rem",
      },
      fontFamily: {
        "headline-md": ["Public Sans"],
        "headline-sm": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "code-sm": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Public Sans"],
        "label-md": ["JetBrains Mono"],
        "body-md": ["Public Sans"],
        "body-sm": ["Public Sans"],
        "headline-xl": ["Public Sans"],
        "headline-xl-mobile": ["Public Sans"],
      },
      fontSize: {
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "code-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-lg": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
export default config;
