"use client";

import { useEffect, useState } from "react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, Area, AreaChart, ComposedChart } from 'recharts';

export default function ForecastChart() {
  const [chartData, setChartData] = useState<any[]>([]);

  useEffect(() => {
    fetch("http://localhost:8000/api/ews/historical-forecast?facility_id=PHC_001&medicine=Paracetamol")
      .then(res => res.json())
      .then(data => setChartData(data.timeseries))
      .catch(err => console.error(err));
  }, []);

  if (chartData.length === 0) return <div>Loading forecast...</div>;

  return (
    <div className="bg-surface-container border border-outline-variant p-4 rounded shadow-sm">
      <div className="flex items-center space-x-2 mb-4 border-b border-outline-variant pb-2">
        <span className="material-symbols-outlined text-secondary">show_chart</span>
        <h2 className="font-headline-sm text-lg font-bold text-on-surface">TFT Multi-Horizon Forecast</h2>
      </div>
      
      <div className="h-64 w-full text-xs">
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={chartData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#c6c6cd" />
            <XAxis dataKey="date" tick={{fontSize: 10}} minTickGap={30} />
            <YAxis />
            <Tooltip />
            <Legend />
            <Area type="monotone" dataKey="ci_upper" fill="#ffdad6" stroke="none" fillOpacity={0.3} />
            <Area type="monotone" dataKey="ci_lower" fill="#ffffff" stroke="none" fillOpacity={1} />
            <Line type="monotone" dataKey="actual_consumption" stroke="#1d4ed8" strokeWidth={2} dot={false} name="Actual Consumption" />
            <Line type="monotone" dataKey="forecasted_demand" stroke="#ba1a1a" strokeDasharray="5 5" strokeWidth={2} dot={false} name="14-Day Forecasted Demand" />
          </ComposedChart>
        </ResponsiveContainer>
      </div>
      <div className="mt-2 text-xs text-on-surface-variant text-center">
        90% Confidence Interval generated by Temporal Fusion Transformer (TFT) edge node.
      </div>
    </div>
  );
}
